### PR TITLE
added onClose event

### PR DESCRIPTION
**Pull request by AlehaWP**
I liked your calendar. But there was not enough opportunity to launch a callback on closing. Added events onClose. If you decide that this might be useful to someone, add it to the main project. I'm not good at TypeScript. If some code is illiterate, do not judge strictly)

### CODE REVIEW

**Comment by avocade** [comment]
Nice, plz merge.

**Comment by uvarov-frontend** [comment]
I'll do it early next week, thank you.

**Comment by uvarov-frontend** [comment]
Look #142 Add hideCalendar() and showCalendar() actions

**Comment by uvarov-frontend** [comment]
Added in v2.7.1

**Comment by avocade** [comment]
🙌🏻

**Pull request merged**
